import React, { createContext, useContext, useState, useEffect } from "react";

export const CURRENCY_SYMBOLS = {
  USD: "$",
  EUR: "€",
  GBP: "£",
  RUB: "₽",
  JPY: "¥",
};

const translations = {
  en: {
    settings: "Settings",
    volume: "Volume",
    theme: "Theme",
    language: "Language",
    playerCustomization: "Player Customization",
    color: "Color",
    shape: "Shape",
    rollDice: "Roll Dice",
    rolling: "Rolling...",
    buyProperty: "Buy",
    pass: "Pass",
    endTurn: "End Turn",
    payJail: "Pay {c}50",
    rollForDoubles: "Roll for Doubles",
    bankrupt: "Bankrupt",
    players: "Players",
    gameLog: "Game Log",
    currentTurn: "Current Turn",
    propertiesOwned: "properties",
    light: "Light",
    dark: "Dark",
    neon: "Neon",
    pastel: "Pastel",
    car: "Car",
    dog: "Dog",
    ship: "Ship",
    hat: "Hat",
    shoe: "Shoe",
    iron: "Iron",
    thimble: "Thimble",
    wheelbarrow: "Wheelbarrow",
    close: "Close",
    monopoly: "MONOPOLY",
    moving: "Moving...",
    player1: "Player 1",
    player2: "Player 2",
    player3: "Player 3",
    player4: "Player 4",
    player5: "Player 5",
    player6: "Player 6",
    numberOfPlayers: "Players (Humans)",
    bots: "Bots",
    maxPlayers: "Total Slots (Limit 6)",
    humanPlayers: "Human Slots",
    fontSans: "Sans",
    fontSerif: "Serif",
    fontMono: "Mono",
    fontComic: "Comic",
    currency: "Currency",
    addBot: "Add Bot",
    addLocalPlayer: "Add Local Player",
    hostControls: "Host Controls",
    syncGameState: "Sync Game State",
    removeBot: "Remove Bot",
    lapsToWin: "Laps to Win",
    leaveRoom: "Leave Room",
    startGame: "Start Game",
    you: "You",
    player: "Player",
    localPlayer: "Local",
    bot: "Bot",
    botName: "Bot {num}",
    // Log messages
    gameStarted: "Game started!",
    bankruptLog: "{player} went bankrupt and is out of the game!",
    rollingForDoublesStatus: "{player} is rolling for doubles...",
    rolled: "{player} rolled {d1} + {d2} = {total}",
    rolledDoublesOutJail: "{player} rolled doubles and left jail!",
    staysInJail: "{player} stays in jail.",
    speedingJail: "{player} was caught speeding and goes to jail!",
    staysInJailStatus: "{player} stays in jail.",
    paidToLeaveStatus: "{player} paid {c}50 to leave jail.",
    paysToLeaveJail: "{player} pays {c}50 to leave jail.",
    passedGo: "{player} passed GO and received {c}200.",
    landedOn: "{player} landed on {square}.",
    goesToJail: "{player} goes to jail!",
    paidTax: "{player} paid {c}{tax} tax.",
    cannotAfford: "{player} cannot afford {square}.",
    paysRent: "{player} pays {c}{rent} rent to {owner}.",
    boughtProperty: "{player} bought {square} for {c}{price}.",
    builtHouseStatus: "{player} built a house on {square}.",
    buildHouseHint: "Click on your properties to build houses (requires monopoly).",
    price: "Price",
    rent: "Rent",
    housePrice: "House Price",
    houses: "Houses",
    hotel: "Hotel",
    mortgage: "Mortgage",
    unmortgage: "Unmortgage",
    sellHouse: "Sell House",
    buildHouse: "Build House",
    trade: "Trade",
    proposeTrade: "Propose Trade",
    accept: "Accept",
    reject: "Reject",
    offer: "Offer",
    request: "Request",
    mortgaged: "MORTGAGED",
    tradeRejected: "Trade rejected by {player}.",
    tradeAccepted: "Trade accepted by {player}!",
    baseRent: "Base Rent",
    rentWithHouses: "Rent with {count} houses",
    rentWithHotel: "Rent with Hotel",
    mortgageValue: "Mortgage Value",
    unmortgageCost: "Unmortgage Cost",
    houseCost: "House Cost",
    hotelCost: "Hotel Cost",
    cancel: "Cancel",
    selectProperties: "Select Properties",
    money: "Money",
    mortgagedStatus: "{player} mortgaged {square}.",
    unmortgagedStatus: "{player} unmortgaged {square}.",
    soldHouseStatus: "{player} sold a house on {square}.",
    tradeOffer: "Trade Offer",
    proposesTrade: "proposes a trade:",
    youGet: "You Get",
    youGive: "You Give",
    noProperties: "No properties",

    // Board Squares
    go: "GO",
    mediterraneanAve: "Mediterranean Avenue",
    communityChest: "Community Chest",
    chest: "Community Chest",
    chance: "Chance",
    balticAve: "Baltic Avenue",
    incomeTax: "Income Tax",
    readingRailroad: "Reading Railroad",
    orientalAve: "Oriental Avenue",
    chance: "Chance",
    vermontAve: "Vermont Avenue",
    connecticutAve: "Connecticut Avenue",
    justVisiting: "Just Visiting",
    stCharlesPlace: "St. Charles Place",
    electricCompany: "Electric Company",
    statesAve: "States Avenue",
    virginiaAve: "Virginia Avenue",
    pennsylvaniaRailroad: "Pennsylvania Railroad",
    stJamesPlace: "St. James Place",
    tennesseeAve: "Tennessee Avenue",
    newYorkAve: "New York Avenue",
    freeParking: "Free Parking",
    kentuckyAve: "Kentucky Avenue",
    indianaAve: "Indiana Avenue",
    illinoisAve: "Illinois Avenue",
    boRailroad: "B. & O. Railroad",
    atlanticAve: "Atlantic Avenue",
    ventnorAve: "Ventnor Avenue",
    waterWorks: "Water Works",
    marvinGardens: "Marvin Gardens",
    goToJailSquare: "Go To Jail",
    pacificAve: "Pacific Avenue",
    northCarolinaAve: "North Carolina Avenue",
    pennsylvaniaAve: "Pennsylvania Avenue",
    shortLine: "Short Line",
    parkPlace: "Park Place",
    luxuryTax: "Luxury Tax",
    boardwalk: "Boardwalk",
    jail: "Jail",
    victory: "VICTORY!",
    conquered: "{player} has conquered the board!",
    playAgain: "Play Again",
    ok: "OK",
    // Chance cards
    chance1: "Bank pays you dividend of {c}50",
    chance2: "Speeding fine {c}15",
    chance3: "You have won a crossword competition. Collect {c}100",
    chance4: "Pay poor tax of {c}15",
    // Community Chest cards
    chest1: "Bank error in your favor. Collect {c}200",
    chest2: "Doctor's fee. Pay {c}50",
    chest3: "From sale of stock you get {c}50",
    chest4: "Pay hospital fees of {c}100",
    mainMenuTitle: "MONOPOLY",
    createRoomBtn: "Create Room",
    joinRoomBtn: "Join Room",
    roomNameLabel: "Room Name",
    lapsToWinLabel: "Laps to Win",
    humanSlotsLabel: "Human Slots",
    botsLabel: "Bots",
    back: "Back",
    create: "Create",
    roomListTitle: "Room List",
    noRooms: "No rooms available",
    playersCount: "Players",
    laps: "Laps",
    playing: "Playing",
    waiting: "Waiting",
    join: "Join",
    yourNickname: "Your Nickname",
    infinite: "∞",
    roomNameDefault: "Room \"{name}\"",

    // Status messages
    waitingForDice: "Waiting for {player} to roll...",
    rollingDice: "{player} is rolling the dice...",
    staysInJailStatus: "{player} stays in jail.",
    movingStatus: "{player} is moving...",
    goesToJailStatus: "{player} goes to jail!",
    paidTaxStatus: "{player} paid tax.",
    drawingCardStatus: "{player} is drawing a card...",
    waitingForDecision: "Waiting for {player}'s decision...",
    endingTurnStatus: "{player} is ending their turn.",
    paidRentStatus: "{player} paid rent.",
    restingStatus: "{player} is resting on their property.",
    boughtPropertyStatus: "{player} bought {square}.",
  },
  ru: {
    settings: "Настройки",
    volume: "Громкость",
    theme: "Тема",
    language: "Язык",
    playerCustomization: "Настройка игроков",
    color: "Цвет",
    shape: "Фигурка",
    rollDice: "Бросить кубики",
    rolling: "Бросаем...",
    buyProperty: "Купить",
    pass: "Пропустить",
    endTurn: "Завершить ход",
    payJail: "Заплатить {c}50",
    rollForDoubles: "Бросить на дубль",
    bankrupt: "Банкрот",
    players: "Игроки",
    gameLog: "Журнал игры",
    currentTurn: "Текущий ход",
    propertiesOwned: "недвижимости",
    light: "Светлая",
    dark: "Темная",
    neon: "Неон",
    pastel: "Пастель",
    car: "Машина",
    dog: "Собака",
    ship: "Корабль",
    hat: "Шляпа",
    shoe: "Башмак",
    iron: "Утюг",
    thimble: "Наперсток",
    wheelbarrow: "Тачка",
    close: "Закрыть",
    monopoly: "МОНОПОЛИЯ",
    moving: "Перемещение...",
    player1: "Игрок 1",
    player2: "Игрок 2",
    player3: "Игрок 3",
    player4: "Игрок 4",
    player5: "Игрок 5",
    player6: "Игрок 6",
    numberOfPlayers: "Игроков (людей)",
    bots: "Ботов",
    maxPlayers: "Всего мест (лимит 6)",
    humanPlayers: "Слотов для людей",
    fontSans: "Без засечек",
    fontSerif: "С засечками",
    fontMono: "Моноширинный",
    fontComic: "Комикс",
    currency: "Валюта",
    addBot: "Добавить бота",
    addLocalPlayer: "Добавить игрока",
    hostControls: "Управление хоста",
    syncGameState: "Синхронизировать состояние",
    removeBot: "Удалить бота",
    lapsToWin: "Кругов для победы",
    leaveRoom: "Выйти из комнаты",
    startGame: "Начать игру",
    you: "Вы",
    player: "Игрок",
    localPlayer: "Локальный",
    bot: "Бот",
    botName: "Бот {num}",
    // Log messages
    gameStarted: "Игра началась!",
    bankruptLog: "{player} обанкротился и выбывает из игры!",
    rollingForDoublesStatus: "{player} бросает на дубль...",
    rolled: "{player} выбросил {d1} + {d2} = {total}",
    rolledDoublesOutJail: "{player} выбросил дубль и вышел из тюрьмы!",
    staysInJail: "{player} остается в тюрьме.",
    speedingJail: "{player} превысил скорость и отправляется в тюрьму!",
    staysInJailStatus: "{player} остается в тюрьме.",
    paidToLeaveStatus: "{player} заплатил {c}50, чтобы выйти из тюрьмы.",
    paysToLeaveJail: "{player} платит {c}50 за выход из тюрьмы.",
    passedGo: "{player} прошел ВПЕРЕД и получил {c}200.",
    landedOn: "{player} попал на {square}.",
    goesToJail: "{player} отправляется в тюрьму!",
    paidTax: "{player} заплатил {c}{tax} налога.",
    cannotAfford: "{player} не может позволить себе {square}.",
    paysRent: "{player} платит {c}{rent} аренды игроку {owner}.",
    boughtProperty: "{player} купил {square} за {c}{price}.",
    builtHouseStatus: "{player} построил дом на {square}.",
    buildHouseHint: "Нажмите на свои участки, чтобы построить дома (нужна монополия).",
    price: "Цена",
    rent: "Аренда",
    housePrice: "Цена дома",
    houses: "Дома",
    hotel: "Отель",
    mortgage: "Заложить",
    unmortgage: "Выкупить",
    sellHouse: "Продать дом",
    buildHouse: "Построить дом",
    trade: "Обмен",
    proposeTrade: "Предложить обмен",
    accept: "Принять",
    reject: "Отклонить",
    offer: "Предлагаю",
    request: "Прошу",
    mortgaged: "ЗАЛОЖЕНО",
    tradeRejected: "{player} отклонил обмен.",
    tradeAccepted: "{player} принял обмен!",
    baseRent: "Базовая аренда",
    rentWithHouses: "Аренда с {count} домами",
    rentWithHotel: "Аренда с отелем",
    mortgageValue: "Стоимость залога",
    unmortgageCost: "Стоимость выкупа",
    houseCost: "Стоимость дома",
    hotelCost: "Стоимость отеля",
    cancel: "Отмена",
    selectProperties: "Выберите участки",
    money: "Деньги",
    mortgagedStatus: "{player} заложил {square}.",
    unmortgagedStatus: "{player} выкупил {square}.",
    soldHouseStatus: "{player} продал дом на {square}.",
    tradeOffer: "Предложение обмена",
    proposesTrade: "предлагает обмен:",
    youGet: "Вы получаете",
    youGive: "Вы отдаете",
    noProperties: "Нет участков",

    // Board Squares
    go: "ВПЕРЕД",
    mediterraneanAve: "Житная улица",
    communityChest: "Сундук",
    chest: "Сундук",
    balticAve: "Нагатинская улица",
    incomeTax: "Подоходный налог",
    readingRailroad: "Рижская железная дорога",
    orientalAve: "Варшавское шоссе",
    chance: "Шанс",
    vermontAve: "Улица Огарева",
    connecticutAve: "Первая парковая улица",
    justVisiting: "Посетитель",
    stCharlesPlace: "Улица Полянка",
    electricCompany: "Электростанция",
    statesAve: "Улица Сретенка",
    virginiaAve: "Ростовская набережная",
    pennsylvaniaRailroad: "Курская железная дорога",
    stJamesPlace: "Рязанский проспект",
    tennesseeAve: "Улица Вавилова",
    newYorkAve: "Рублевское шоссе",
    freeParking: "Бесплатная парковка",
    kentuckyAve: "Улица Тверская",
    indianaAve: "Пушкинская улица",
    illinoisAve: "Площадь Маяковского",
    boRailroad: "Казанская железная дорога",
    atlanticAve: "Улица Грузинский вал",
    ventnorAve: "Новинский бульвар",
    waterWorks: "Водопровод",
    marvinGardens: "Смоленская площадь",
    goToJailSquare: "Отправляйтесь в тюрьму",
    pacificAve: "Улица Щусева",
    northCarolinaAve: "Гоголевский бульвар",
    pennsylvaniaAve: "Кутузовский проспект",
    shortLine: "Ленинградская железная дорога",
    parkPlace: "Улица Малая Бронная",
    luxuryTax: "Налог на роскошь",
    boardwalk: "Улица Арбат",
    jail: "Тюрьма",
    victory: "ПОБЕДА!",
    conquered: "{player} покорил игровое поле!",
    playAgain: "Играть снова",
    ok: "ОК",
    // Chance cards
    chance1: "Банк выплачивает вам дивиденды в размере {c}50",
    chance2: "Штраф за превышение скорости {c}15",
    chance3: "Вы выиграли конкурс кроссвордов. Получите {c}100",
    chance4: "Заплатите налог для бедных в размере {c}15",
    // Community Chest cards
    chest1: "Банковская ошибка в вашу пользу. Получите {c}200",
    chest2: "Взнос врачу. Заплатите {c}50",
    chest3: "Доход от продажи акций {c}50",
    chest4: "Заплатите больничный сбор {c}100",
    mainMenuTitle: "МОНОПОЛИЯ",
    createRoomBtn: "Создать комнату",
    joinRoomBtn: "Присоединиться",
    roomNameLabel: "Название комнаты",
    lapsToWinLabel: "Кругов для победы",
    humanSlotsLabel: "Слотов для людей",
    botsLabel: "Ботов",
    back: "Назад",
    create: "Создать",
    roomListTitle: "Список комнат",
    noRooms: "Нет доступных комнат",
    playersCount: "Игроков",
    laps: "Кругов",
    playing: "В игре",
    waiting: "Ожидание",
    join: "Войти",
    yourNickname: "Ваш никнейм",
    infinite: "∞",
    roomNameDefault: "Комната \"{name}\"",
    
    // Status messages
    waitingForDice: "Ожидаем пока {player} кинет кубики...",
    rollingDice: "{player} бросает кубики...",
    staysInJailStatus: "{player} остается в тюрьме.",
    movingStatus: "{player} перемещается...",
    goesToJailStatus: "{player} отправляется в тюрьму!",
    paidTaxStatus: "{player} заплатил налог.",
    drawingCardStatus: "{player} тянет карточку...",
    waitingForDecision: "Ожидаем решения {player}...",
    endingTurnStatus: "{player} завершает ход.",
    paidRentStatus: "{player} заплатил аренду.",
    restingStatus: "{player} отдыхает на своей собственности.",
    boughtPropertyStatus: "{player} купил {square}!",
    
    // Camera & UI
    camera: "Камера",
    topLeft: "Левый верхний угол",
    topRight: "Правый верхний угол",
    bottomLeft: "Левый нижний угол",
    bottomRight: "Правый нижний угол",
    auto: "Автоматически",
    fullView: "Весь вид",
    actions: "Действия",
    
    // Log dynamic messages
    waitingForDecisionLog: "Ожидаем решения {player}...",
    rollingDiceLog: "Бросок кубиков...",
    diceResultLog: "Результат: {total}",
    landedOnLog: "{player} попал на {square}{price}",
    boughtPropertyLog: "{player} купил {square} за {c}{price}",
    paidRentLog: "{player} заплатил ренту {c}{rent} игроку {owner}",
    paidTaxLog: "{player} заплатил налог {c}{tax}",
    drewCardLog: "{player} вытянул карточку {type}",
  },
};

const SettingsContext = createContext(undefined);

export const SettingsProvider = ({ children }) => {
  const [volume, setVolume] = useState(0.5);
  const [theme, setTheme] = useState("light");
  const [language, setLanguage] = useState("ru");
  const [font, setFont] = useState("sans");
  const [currency, setCurrency] = useState("USD");
  const [playerName, setPlayerName] = useState(
    () => localStorage.getItem("playerName") || "Игрок",
  );
  const colors = ["#ef4444", "#3b82f6", "#10b981", "#f59e0b", "#8b5cf6", "#ec4899", "#06b6d4", "#f97316"];
  const [playerColor, setPlayerColor] = useState(
    () => localStorage.getItem("playerColor") || colors[Math.floor(Math.random() * colors.length)],
  );
  const [userId] = useState(() => {
    const saved = localStorage.getItem("monopoly_userId");
    if (saved) return saved;
    const newId = `user_${Math.random().toString(36).substring(2, 10)}`;
    localStorage.setItem("monopoly_userId", newId);
    return newId;
  });

  useEffect(() => {
    document.documentElement.setAttribute("data-theme", theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.setAttribute("data-font", font);
  }, [font]);

  useEffect(() => {
    localStorage.setItem("playerName", playerName);
  }, [playerName]);

  useEffect(() => {
    localStorage.setItem("playerColor", playerColor);
  }, [playerColor]);

  const t = (key, params = {}) => {
    let str = translations[language][key] || key;
    if (typeof str === "string") {
      str = str.replace(/\{c\}/g, CURRENCY_SYMBOLS[currency]);
      Object.keys(params).forEach(param => {
        str = str.replace(new RegExp(`\\{${param}\\}`, 'g'), params[param]);
      });
    }
    return str;
  };

  return (
    <SettingsContext.Provider
      value={{
        volume,
        setVolume,
        theme,
        setTheme,
        language,
        setLanguage,
        font,
        setFont,
        currency,
        setCurrency,
        currencySymbol: CURRENCY_SYMBOLS[currency],
        playerName,
        setPlayerName,
        playerColor,
        setPlayerColor,
        userId,
        t,
      }}
    >
      {children}
    </SettingsContext.Provider>
  );
};

export const useSettings = () => {
  const context = useContext(SettingsContext);
  if (!context)
    throw new Error("useSettings must be used within SettingsProvider");
  return context;
};
